#!/usr/bin/env python3
"""Random facet search with exact RC2 evaluation for an n=8 counterexample.

This is materially different from the joint CP-SAT/SMT encodings.  In the
lossless minimal normal form, F is generated by its inclusion-maximal members,
and those facets are members of the intersecting witness, hence are pairwise
intersecting.  We sample such facet antichains, build F exactly, and solve the
maximum-intersecting-subfamily problem on F as a weighted partial MaxSAT
instance.  A positive beta(F)-max_star(F) is a definition-level counterexample.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import time
from pathlib import Path

from pysat.examples.rc2 import RC2
from pysat.formula import WCNF


N = 8
M = 1 << N
FULL = M - 1


def closure(facets: list[int]) -> list[int]:
    present = {0}
    present.update(1 << x for x in range(N))
    for top in facets:
        sub = top
        while True:
            present.add(sub)
            if sub == 0:
                break
            sub = (sub - 1) & top
    return sorted(present)


def exact_beta(family: list[int]) -> tuple[int, list[int]]:
    vertices = [s for s in family if s != 0]
    var = {s: i + 1 for i, s in enumerate(vertices)}
    wcnf = WCNF()
    for i, s in enumerate(vertices):
        for t in vertices[i + 1:]:
            if (s & t) == 0:
                wcnf.append([-var[s], -var[t]])
    for s in vertices:
        wcnf.append([var[s]], weight=1)
    with RC2(wcnf, solver="g4", adapt=True, exhaust=True, incr=False) as rc2:
        model = rc2.compute()
        if model is None:
            raise RuntimeError("RC2 unexpectedly found no model")
        chosen = [s for s in vertices if var[s] in model]
        return len(chosen), chosen


def random_facets(rng: random.Random) -> list[int]:
    # A broad mixture: sparse facet systems keep F small; denser ones explore
    # the difficult near-full regimes where equality examples are common.
    target = rng.randint(2, 24)
    facets: list[int] = []
    sizes = [2, 3, 3, 4, 4, 4, 5, 5, 6, 7]
    attempts = 0
    while len(facets) < target and attempts < 20 * target + 100:
        attempts += 1
        k = rng.choice(sizes)
        bits = rng.sample(range(N), k)
        cand = sum(1 << x for x in bits)
        if all(cand & old for old in facets):
            facets = [old for old in facets if (old & cand) not in (old, cand)]
            if cand not in facets:
                facets.append(cand)

    # Force full support without destroying pairwise intersection: enlarge a
    # random facet by each missing element, replacing contained facets.
    used = 0
    for s in facets:
        used |= s
    for x in range(N):
        if not used & (1 << x):
            if not facets:
                facets = [1 | (1 << x)]
            else:
                j = rng.randrange(len(facets))
                facets[j] |= 1 << x
            used |= 1 << x

    # Canonical antichain cleanup.
    unique = sorted(set(facets))
    return [s for s in unique if not any(s != t and (s & t) == s for t in unique)]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seconds", type=float, default=600.0)
    ap.add_argument("--seed", type=int, default=27010803)
    ap.add_argument("--out", type=Path, default=Path("facet_rc2_result.json"))
    args = ap.parse_args()
    rng = random.Random(args.seed)
    started = time.time()
    evaluated = 0
    best: dict | None = None
    score_hist: dict[int, int] = {}
    seen: set[tuple[int, ...]] = set()

    while time.time() - started < args.seconds:
        facets = random_facets(rng)
        key = tuple(facets)
        if key in seen:
            continue
        seen.add(key)
        family = closure(facets)
        beta, witness = exact_beta(family)
        stars = [sum(1 for s in family if s & (1 << x)) for x in range(N)]
        score = beta - max(stars)
        score_hist[score] = score_hist.get(score, 0) + 1
        evaluated += 1
        record = {
            "score": score,
            "facets": facets,
            "family_masks": family,
            "family_size": len(family),
            "star_sizes": stars,
            "maximum_intersecting_size": beta,
            "maximum_intersecting_masks": witness,
        }
        if best is None or (score, beta, -len(family)) > (
            best["score"], best["maximum_intersecting_size"], -best["family_size"]
        ):
            best = record
            print(json.dumps({"evaluated": evaluated, "new_best": record}, sort_keys=True), flush=True)
        if score > 0:
            break

    elapsed = time.time() - started
    result = {
        "schema": "erdos701-n8-random-facets-rc2-v1",
        "engine": "random pairwise-intersecting facet antichains + exact RC2 MaxSAT",
        "parameters": {"seconds": args.seconds, "seed": args.seed, "out": str(args.out)},
        "elapsed_seconds": elapsed,
        "distinct_facet_systems_evaluated": evaluated,
        "score_histogram": {str(k): v for k, v in sorted(score_hist.items())},
        "best": best,
        "status": "COUNTEREXAMPLE_CANDIDATE" if best and best["score"] > 0 else "NO_HIT_BOUNDED_SEARCH",
        "coverage_claim": "heuristic sample only; not exhaustive",
    }
    payload = json.dumps(result, indent=2, sort_keys=True) + "\n"
    args.out.write_bytes(payload.encode())
    print(json.dumps({
        "status": result["status"],
        "evaluated": evaluated,
        "best_score": None if best is None else best["score"],
        "elapsed_seconds": elapsed,
        "sha256": hashlib.sha256(payload.encode()).hexdigest(),
    }, sort_keys=True))


if __name__ == "__main__":
    main()
