#!/usr/bin/env python3
"""Independent direct Z3 encoding for an n=8 Chvatal counterexample."""

from __future__ import annotations

import argparse
import hashlib
import json
import time
from pathlib import Path

import z3


def bitsets(n: int = 8) -> range:
    return range(1 << n)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seconds", type=int, default=900)
    ap.add_argument("--seed", type=int, default=17010803)
    ap.add_argument(
        "--bare",
        action="store_true",
        help="Use only definition-level constraints; omit lossless strengthenings.",
    )
    ap.add_argument(
        "--normal-form",
        action="store_true",
        help="Assume F is exactly the down-closure generated by A plus singletons.",
    )
    ap.add_argument(
        "--maximality",
        action="store_true",
        help="Require A to be inclusion-maximal among intersecting subfamilies of F.",
    )
    ap.add_argument(
        "--full-support",
        action="store_true",
        help="Require union(A)=[8], lossless using the certified n<=7 theorem.",
    )
    ap.add_argument("--out", type=Path, default=Path("z3_result.json"))
    args = ap.parse_args()
    n = 8
    masks = list(bitsets(n))
    full = (1 << n) - 1
    f = {s: z3.Bool(f"F{s}") for s in masks}
    a = {s: z3.Bool(f"A{s}") for s in masks}
    solver = z3.Solver()
    solver.set(timeout=args.seconds * 1000)
    solver.set(random_seed=args.seed)
    counts = {"down": 0, "subset": 0, "disjoint": 0, "upclosure": 0,
              "normal_form": 0, "maximality": 0, "star_order": 0,
              "full_support": 0, "strict_gap": 0}

    solver.add(f[0])
    solver.add(z3.Not(a[0]))
    for x in range(n):
        solver.add(f[1 << x])
        if not args.bare:
            solver.add(z3.Not(a[1 << x]))

    # Downward closure, deliberately encoded with all subset pairs rather than
    # CP-SAT's immediate-subset formulation.
    for s in masks:
        t = s
        while True:
            if t != s:
                solver.add(z3.Implies(f[s], f[t]))
                counts["down"] += 1
            if t == 0:
                break
            t = (t - 1) & s

    for s in masks:
        solver.add(z3.Implies(a[s], f[s]))
        counts["subset"] += 1

    if args.full_support:
        for x in range(n):
            solver.add(z3.Or([a[s] for s in masks[1:] if s & (1 << x)]))
            counts["full_support"] += 1

    if args.normal_form:
        for s in masks:
            if s.bit_count() >= 2:
                supersets = [a[t] for t in masks if (t & s) == s]
                solver.add(z3.Implies(f[s], z3.Or(supersets)))
                counts["normal_form"] += 1

    for i, s in enumerate(masks):
        if s == 0:
            continue
        for t in masks[i + 1:]:
            if (s & t) == 0:
                solver.add(z3.Or(z3.Not(a[s]), z3.Not(a[t])))
                counts["disjoint"] += 1

    # Choose a maximal extension of the witness A within F.
    if not args.bare:
        for s in masks[1:]:
            outside = full ^ s
            add = outside
            while add:
                t = s | add
                solver.add(z3.Implies(z3.And(a[s], f[t]), a[t]))
                counts["upclosure"] += 1
                add = (add - 1) & outside

    if args.maximality:
        for t in masks:
            blockers = [a[s] for s in masks[1:] if (s & t) == 0]
            solver.add(z3.Implies(z3.And(f[t], z3.Not(a[t])), z3.Or(blockers)))
            counts["maximality"] += 1

    def isum(bs: list[z3.BoolRef]) -> z3.ArithRef:
        return z3.Sum([z3.If(b, 1, 0) for b in bs])

    asize = isum([a[s] for s in masks])
    stars = [isum([f[s] for s in masks if s & (1 << x)]) for x in range(n)]
    if not args.bare:
        for x in range(n - 1):
            solver.add(stars[x] >= stars[x + 1])
            counts["star_order"] += 1
    for x in range(n):
        solver.add(asize > stars[x])
        counts["strict_gap"] += 1

    started = time.time()
    answer = solver.check()
    elapsed = time.time() - started
    status = "SAT" if answer == z3.sat else "UNSAT" if answer == z3.unsat else "UNKNOWN_TIMEOUT"
    family = witness = star_values = None
    reason_unknown = None
    if answer == z3.sat:
        model = solver.model()
        family = [s for s in masks if z3.is_true(model.eval(f[s], model_completion=True))]
        witness = [s for s in masks if z3.is_true(model.eval(a[s], model_completion=True))]
        star_values = [sum(1 for s in family if s & (1 << x)) for x in range(n)]
    elif answer == z3.unknown:
        reason_unknown = solver.reason_unknown()

    stats = {str(k): str(v) for k, v in solver.statistics()}
    result = {
        "schema": "erdos701-n8-z3-v1",
        "engine": "Z3 SMT",
        "parameters": vars(args) | {"out": str(args.out)},
        "constraint_counts": counts,
        "status": status,
        "reason_unknown": reason_unknown,
        "elapsed_seconds": elapsed,
        "family_masks": family,
        "witness_masks": witness,
        "star_sizes": star_values,
        "witness_size": None if witness is None else len(witness),
        "solver_statistics": stats,
        "conventions": {
            "ground_union_exactly_8": True,
            "empty_in_F": True,
            "empty_in_A": False,
            "bare_definition_level_formulation": args.bare,
            "minimal_downclosure_normal_form": args.normal_form,
            "inclusion_maximal_witness": args.maximality,
            "full_support_using_certified_n_le_7_result": args.full_support,
            "singletons_in_A_excluded_losslessly": not args.bare,
            "A_upward_closed_in_F_by_maximal_extension": not args.bare,
            "star_order_symmetry_break_lossless": not args.bare,
        },
    }
    payload = json.dumps(result, indent=2, sort_keys=True) + "\n"
    args.out.write_bytes(payload.encode())
    print(json.dumps({
        "status": status,
        "elapsed_seconds": elapsed,
        "reason_unknown": reason_unknown,
        "family_size": None if family is None else len(family),
        "witness_size": None if witness is None else len(witness),
        "sha256": hashlib.sha256(payload.encode()).hexdigest(),
    }, sort_keys=True))


if __name__ == "__main__":
    main()
