#!/usr/bin/env python3
"""Direct CP-SAT counterexample search for Chvatal's conjecture on [8]."""

from __future__ import annotations

import argparse
import hashlib
import json
import time
from pathlib import Path

from ortools.sat.python import cp_model


N = 8
M = 1 << N


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seconds", type=float, default=900.0)
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--seed", type=int, default=7010803)
    ap.add_argument(
        "--bare",
        action="store_true",
        help="Use only definition-level constraints; omit lossless strengthenings.",
    )
    ap.add_argument(
        "--normal-form",
        action="store_true",
        help="Assume F is exactly the down-closure generated by A plus singletons.",
    )
    ap.add_argument(
        "--maximality",
        action="store_true",
        help="Require A to be inclusion-maximal among intersecting subfamilies of F.",
    )
    ap.add_argument(
        "--optimize-gap",
        action="store_true",
        help="Maximize min_x(|A|-|F_x|) instead of requiring it to be positive.",
    )
    ap.add_argument(
        "--full-support",
        action="store_true",
        help="Require union(A)=[8], lossless using the certified n<=7 theorem.",
    )
    ap.add_argument(
        "--gap-floor",
        type=int,
        default=None,
        help="Optional lower bound on the optimized minimum star gap.",
    )
    ap.add_argument("--near-model", type=Path, default=None)
    ap.add_argument("--radius-min", type=int, default=0)
    ap.add_argument("--radius-max", type=int, default=None)
    ap.add_argument("--hint-near", action="store_true")
    ap.add_argument("--out", type=Path, default=Path("cpsat_result.json"))
    args = ap.parse_args()

    model = cp_model.CpModel()
    f = [model.new_bool_var(f"f_{s:03d}") for s in range(M)]
    a = [model.new_bool_var(f"a_{s:03d}") for s in range(M)]
    counts = {"down": 0, "subset": 0, "disjoint": 0, "upclosure": 0,
              "normal_form": 0, "maximality": 0, "star_order": 0,
              "full_support": 0, "hamming_neighborhood": 0,
              "strict_gap": 0, "gap_bound": 0}

    # A nonempty downset contains the empty set.  Intersecting families use
    # the non-vacuous convention, so the empty set is never in A.
    model.add(f[0] == 1)
    model.add(a[0] == 0)

    # Union(F)=[8] is equivalent, for a downset, to including every singleton.
    for x in range(N):
        model.add(f[1 << x] == 1)
        # Any witness containing a singleton {x} is contained in the x-star
        # and cannot beat that star, so these are losslessly excluded.
        if not args.bare:
            model.add(a[1 << x] == 0)

    # Immediate-subset closure is equivalent to full downward closure.
    for s in range(1, M):
        for x in range(N):
            if s & (1 << x):
                model.add(f[s] <= f[s ^ (1 << x)])
                counts["down"] += 1

    for s in range(M):
        model.add(a[s] <= f[s])
        counts["subset"] += 1

    if args.full_support:
        for x in range(N):
            model.add_bool_or([a[s] for s in range(1, M) if s & (1 << x)])
            counts["full_support"] += 1

    # Lossless normal form for counterexample discovery.  Starting from any
    # witness (F,A), replace F by down(A) plus all singletons.  This remains a
    # downset on [8], contains A, and can only shrink every star.  For sets of
    # size at least two, exactness is the reverse implication below; the
    # forward implication follows from a<=f and downward closure.
    if args.normal_form:
        for s in range(M):
            if s.bit_count() >= 2:
                supersets = [a[t] for t in range(M) if (t & s) == s]
                model.add_bool_or([f[s].Not()] + supersets)
                counts["normal_form"] += 1

    # Pairwise intersection.  a[0]=0 handles the empty-set convention.
    for s in range(1, M):
        for t in range(s + 1, M):
            if s & t == 0:
                model.add(a[s] + a[t] <= 1)
                counts["disjoint"] += 1

    # We may choose A inclusion-maximal inside F.  If S in A and S subset T
    # in F, then adding T preserves intersection, hence T is also in A.
    if not args.bare:
        for s in range(1, M):
            remaining = (M - 1) ^ s
            sub = remaining
            while sub:
                t = s | sub
                model.add(a[s] + f[t] <= 1 + a[t])
                counts["upclosure"] += 1
                sub = (sub - 1) & remaining

    # A witness can be extended, without changing F, to an inclusion-maximal
    # intersecting family.  Every omitted T in F must then have an A-member
    # disjoint from T.  This is stronger than relative up-closure and is also
    # lossless for existence.
    if args.maximality:
        for t in range(M):
            blockers = [a[s] for s in range(1, M) if (s & t) == 0]
            model.add_bool_or([f[t].Not(), a[t]] + blockers)
            counts["maximality"] += 1

    if args.near_model is not None:
        near = json.loads(args.near_model.read_text(encoding="utf-8"))
        near_f = set(near["family_masks"])
        near_a = set(near["witness_masks"])
        differences = [1 - f[s] if s in near_f else f[s] for s in range(M)]
        differences += [1 - a[s] if s in near_a else a[s] for s in range(M)]
        distance = sum(differences)
        model.add(distance >= args.radius_min)
        if args.radius_max is not None:
            model.add(distance <= args.radius_max)
        counts["hamming_neighborhood"] += 1
        if args.hint_near:
            for s in range(M):
                model.add_hint(f[s], int(s in near_f))
                model.add_hint(a[s], int(s in near_a))

    acount = sum(a)
    stars = [sum(f[s] for s in range(M) if s & (1 << x)) for x in range(N)]

    # Lossless element relabelling: order stars nonincreasingly.
    if not args.bare:
        for x in range(N - 1):
            model.add(stars[x] >= stars[x + 1])
            counts["star_order"] += 1

    gap = None
    if args.optimize_gap:
        gap = model.new_int_var(-128, 256, "minimum_star_gap")
        for x in range(N):
            model.add(gap <= acount - stars[x])
            counts["gap_bound"] += 1
        if args.gap_floor is not None:
            model.add(gap >= args.gap_floor)
        model.maximize(gap)
    else:
        # One intersecting witness beats every star by at least one.
        for x in range(N):
            model.add(acount >= stars[x] + 1)
            counts["strict_gap"] += 1

    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = args.seconds
    solver.parameters.num_search_workers = args.workers
    solver.parameters.random_seed = args.seed
    solver.parameters.log_search_progress = False
    solver.parameters.cp_model_presolve = True

    started = time.time()
    status = solver.solve(model)
    elapsed = time.time() - started
    names = {
        cp_model.OPTIMAL: "SAT_OPTIMAL",
        cp_model.FEASIBLE: "SAT_FEASIBLE",
        cp_model.INFEASIBLE: "UNSAT",
        cp_model.MODEL_INVALID: "MODEL_INVALID",
        cp_model.UNKNOWN: "UNKNOWN_TIMEOUT",
    }
    status_name = names.get(status, f"STATUS_{status}")
    family = witness = None
    star_values = None
    gap_value = None
    if status in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        family = [s for s in range(M) if solver.value(f[s])]
        witness = [s for s in range(M) if solver.value(a[s])]
        star_values = [solver.value(z) for z in stars]
        gap_value = min(len(witness) - z for z in star_values)

    result = {
        "schema": "erdos701-n8-cpsat-v1",
        "engine": "OR-Tools CP-SAT",
        "parameters": {
            k: str(v) if isinstance(v, Path) else v
            for k, v in vars(args).items()
        },
        "constraint_counts": counts,
        "status": status_name,
        "elapsed_seconds": elapsed,
        "wall_time_limit_seconds": args.seconds,
        "family_masks": family,
        "witness_masks": witness,
        "star_sizes": star_values,
        "witness_size": None if witness is None else len(witness),
        "minimum_star_gap": gap_value,
        "solver": {
            "conflicts": solver.num_conflicts,
            "branches": solver.num_branches,
            "best_objective_bound": solver.best_objective_bound,
            "wall_time": solver.wall_time,
            "response_stats": solver.response_stats(),
        },
        "conventions": {
            "ground_union_exactly_8": True,
            "empty_in_F": True,
            "empty_in_A": False,
            "bare_definition_level_formulation": args.bare,
            "minimal_downclosure_normal_form": args.normal_form,
            "inclusion_maximal_witness": args.maximality,
            "full_support_using_certified_n_le_7_result": args.full_support,
            "singletons_in_A_excluded_losslessly": not args.bare,
            "A_upward_closed_in_F_by_maximal_extension": not args.bare,
            "star_order_symmetry_break_lossless": not args.bare,
        },
    }
    payload = json.dumps(result, indent=2, sort_keys=True) + "\n"
    args.out.write_bytes(payload.encode())
    print(json.dumps({
        "status": status_name,
        "elapsed_seconds": elapsed,
        "family_size": None if family is None else len(family),
        "witness_size": None if witness is None else len(witness),
        "sha256": hashlib.sha256(payload.encode()).hexdigest(),
    }, sort_keys=True))


if __name__ == "__main__":
    main()
